os:
  - linux
language: node_js
node_js:
  - "4.4.3"
jdk:
  - oraclejdk8
sudo: false
before_install: npm install -g grunt-cli
install: npm install
before_script: grunt build
notifications:
  slack: gui-team:aDCNycEgsrZg2fssvHq5NkoB
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
