os:
  - linux
sudo: required
dist: trusty
language:
  - node_js
  - java
node_js:
  - "4.4.4"
jdk:
  - oraclejdk8
before_install:
  - npm install -g bower
  - npm install -g grunt-cli
install:
  - npm install
  - bower install
#before_script: grunt build
script:
  - mvn test
  - grunt test
notifications:
  email: false
  slack: gui-team:aDCNycEgsrZg2fssvHq5NkoB
  webhooks:
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
